spring.application.name=periferia

server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/periferiadb
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8181

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=periferia-jwt-secret-key-change-this-in-production-256bits
app.jwt.expiration-ms=86400000
